openapi: 3.0.0
info:
  title: gradedShop
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /postings/creatEdit:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-postings-creatEdit
  /searchPostings:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-searchPostings
  /registration:
    get:
      summary: User registration
      tags: []
      responses: {}
      operationId: get-registration
    post:
      summary: ''
      operationId: post-registration
      responses:
        '200':
          description: OK
      description: This endpoint is used to create an user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                birthDate:
                  type: string
                  description: ISO 8601
                eMail:
                  type: string
                phoneNumber:
                  type: string
                userName:
                  type: string
                passWord:
                  type: string
              required:
                - fullName
                - birthDate
                - eMail
                - phoneNumber
                - userName
                - passWord
            examples:
              example-1:
                value:
                  fullName: Name Namersson
                  birthDate: '2020-10-06'
                  eMail: string
                  phoneNumber: string
                  userName: NamNam
                  passWord: string
components:
  schemas: {}
