openapi: 3.0.0
info:
  title: gradedShop
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /postings/creatEdit:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-postings-creatEdit
  /searchPostings:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-searchPostings
  /registration:
    get:
      summary: User registration
      tags: []
      responses: {}
      operationId: get-registration
    post:
      summary: ''
      operationId: post-registration
      responses:
        '200':
          description: OK
      description: This endpoint is used to create an user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                birthDate:
                  type: string
                eMail:
                  type: string
                phoneNumber:
                  type: string
                userName:
                  type: string
                passWord:
                  type: string
components:
  schemas: {}
