openapi: 3.0.0
info:
  title: gradedShop
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /postings/creatEdit:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-postings-creatEdit
  /searchPostings:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-searchPostings
components:
  schemas: {}
