openapi: 3.0.0
info:
  title: gradedShop
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /registration:
    post:
      summary: ''
      operationId: post-registration
      responses:
        '201':
          description: User created succesfully!
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: integer
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorDescription:
                    type: string
              examples:
                example-1:
                  value:
                    '': string
      description: This endpoint is used to create an user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                birthDate:
                  type: string
                  description: ISO 8601
                eMail:
                  type: string
                  format: email
                userName:
                  type: string
                passWord:
                  type: string
                  format: password
              required:
                - fullName
                - birthDate
                - eMail
                - userName
                - passWord
            examples:
              example-1:
                value:
                  fullName: Name Namersson
                  birthDate: '2020-10-06'
                  eMail: example@examplemail.com
                  userName: NamNam
                  passWord: examplePassWord
  /posting:
    get:
      summary: Posting operations
      tags: []
      responses: {}
      operationId: get-posting
    post:
      summary: ''
      operationId: post-posting
      responses:
        '200':
          description: OK
      description: Create a new posting
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category:
                  type: string
                images:
                  type: object
                  properties:
                    imageOne:
                      type: object
                    imageTwo:
                      type: object
                    imageThree:
                      type: object
                    imageFour:
                      type: object
                askingPrice:
                  type: number
                postDate:
                  type: string
                location:
                  type: object
                  properties:
                    town:
                      type: string
                    country:
                      type: string
                    address:
                      type: string
                    zipCode:
                      type: string
                deliveryTYpe:
                  type: object
                  properties:
                    shipping:
                      type: string
                    pickup:
                      type: string
                seller:
                  type: object
                  properties:
                    sellerName:
                      type: string
                    eMail:
                      type: string
                    phoneNumber:
                      type: string
components:
  schemas: {}
